server:
  ip: 127.0.0.1
  port: 8100
#  ssl:
#    key-store: classpath:easyverify-api.iskwen.com.jks
#    key-store-password: qq19971102
#    key-store-type: JKS
spring:
  application:
    name: cloud-aggregation-api
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: ${server.ip}:8848
        group: DEFAULT_GROUP #默认是DEFAULT_GROUP，也可以自己自行指定
      config:
        server-addr: ${server.ip}:8848
        file-extension: yaml
        group: DEFAULT_GROUP #默认是DEFAULT_GROUP，也可以自己自行指定
    sentinel:
      transport:
        dashboard: ${server.ip}:8080
        port: 8719 #默认8719，被占用的话会自动向8720后进行扫描
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

jwt:
  config:
    salt: 4ng5X0QvsrxVxFJoiJ5OG5TuksD3EqnO20UcklVk7qMPC0eqq2fETopcFWK8fDCH
    ttl: 10368000000

ribbon:
  #处理请求的超时时间，5秒
  ReadTimeout:  5000
  #连接建立的超时时长，5秒
  ConnectTimeout: 5000
  #同一台实例的最大重试次数，但是不包括首次调用，默认为1次
  MaxAutoRetries: 1
  #重试负载均衡其他实例的最大重试次数，不包括首次调用，默认为0次
  MaxAutoRetriesNextServer: 0
  #/是否对所有操作都重试，默认false
  OkToRetryOnAllOperations: false