spring:
  profiles:
    active: dev # 表示开发环境
    #active: dev # 表示开发环境
    #active: test # 表示测试环境
    #active: prod #表示生产环境
jwt:
  config:
    salt: 4ng5X0QvsrxVxFJoiJ5OG5TuksD3EqnO20UcklVk7qMPC0eqq2fETopcFWK8fDCH
    ttl: 10368000000